#pragma config(Sensor, S1,     WallSensor,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ColorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     BallSensor,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          ClawMotor,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          ArmMotor,	tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This file locates a ball

// Including the ball file
//#include "FinallyHelpUs2v1.c"

// Including the going back home file
//#include "FinallyHelpUs3v1.c"



//This is the set threshold I think we got somewhere from 40 to 50 will work

int minDist = 5;
int maxDist = 15;
int speedMotor = 20;
int direction = 1;

enum Directions
{
	forwardDir = 0,
	leftSoft = 25,
	rightSoft = -25,
	leftHard = 75,
	rightHard = -75
};

enum Colors
{
	yellow = 0,
	red = 1
};

enum Speed
{
	normal = -40,
	softTurn = -30,
	hardTurn = -20,
	reverseNormal = 40,
	stopMovement = 0
};

// Top distance sensor for the wall
bool enableWallSensor = false;
int stateWallSensor = 0;

// Bottom distance sensor for the ball
bool enableBallSensor = false;
int stateBallSensor = 0;

// Color sensor to detect ball color
bool enableColorSensor = false;
bool stateColorSensor = false;

// true = right, false = left
bool lastTurn = true;

enum stateValue
{
	start,
    ball,
	home
};

task letsFindBall() {
	short sensorValWall = 0;
	short sensorValBall = 0;

	sensorValWall = SensorValue(DistSensor);
	sensorValBall - SensorValue(BallSensor);

	while(stateValue != ball) {

		// spin-searches for the ball
		int speed = 20;
		int maybeBall = 0;
		bool spinning = true;
		setMotorSync(RightMotor, LeftMotor, -75, speed);

		while (spinning == true) {
			if (enableWallSensor == false && enableBallSensor == true) {
				// slows down to check if ball is found
				speed = 5;
				maybeBall = maybeBall + 1;
				if ((enableWallSensor == false) && (enableBallSensor == true) && (maybeBall == 5)) {
					maybeBall = maybeBall + 1;
				// changes to obtainBall task
				stateValue = ball;
				wait1Msec(3);
			}
			else if (WallSensor == true && BallSensor == false) {
				// turns
				setMotorSync(RightMotor, LeftMotor, -99, 20)

			}
			else if (WallSensor = false && BallSensor = false) {

				wait1Msec(100);
			}
	  		else {

	  		}
		}
	releaseCPU();
}

task obtainBall() {
	short sensorValBall = 0;

	// this below needs worked on
	stateValue
	while(true) {
			sensorValWall = SensorValue(DistSensor);

			if (sensorVal < minDist) {
				// If the color is black on each then
				stateDistSensor = tooClose;
			} else {
				stateDistSensor = good;
			}
			wait1Msec(3);
		}
		else {
			wait1Msec(100);
		}
	}
	releaseCPU();
}

task main()
{
	enableWallSensor = true;
	enableBallSensor = true;
	enableColorSensor = true;

	//begins subthread
	while(true) {
		stateValue = start;
		if (stateValue == start) {
			startTask(letsFindBall);
		}
		if (stateValue == ball) {
			startTask(obtainBall);
		}
		if (stateValue == home) {
			startTask(returnHome);
		}
		false;
	}
	releaseCPU();
}
