#pragma config(Sensor, S1,     LeftLight,      sensorColorNxtFULL)
#pragma config(Sensor, S4,     RightLight,     sensorColorNxtFULL)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is the set threshold I think we got somewhere from 40 to 50 will work

int satThreshold = 55;
int speedSens = 50;
int direction = 1;
int leftSoft = 50;
int rightSoft = -50;
int leftHard = 99;
int rightHard = -99;

bool enableLights = false;
int stateLightSensor = 0;

enum
{
		noneDark = 0,
    leftDark = 1,
    rightDark = 2,
    bothDark = 3
};


bool locked = false;

task moveSense() {
	short leftColor = 0;
	short rightColor = 0;

	while(true) {
		short lastColorLeft = leftColor;
		short lastColorRight = rightColor;
		//If equal to the last then go straight
		// if last was both black then veer right
		// if color is white and last was black then reverse and turn?
		// if color is white and one was black turn to the one that was black and reverse a bit
		// have a wait at the end
		leftColor = SensorValue(LeftLight);
		rightColor = SensorValue(RightLight);



		if (leftColor < satThreshold && rightColor < satThreshold){
			// If the color is white on each then
			direction = 0;


			} else {


			if (leftColor > satThreshold && rightColor > satThreshold) {
				//If the color is black on both reverse the other motor and turn harder

				if(direction == leftSoft) {
					direction = leftHard;
				}

				if(direction == rightSoft) {
					direction = rightHard;
				}

				} else {
				if (leftColor > satThreshold && rightColor < satThreshold) {
					//turn left soft, left is black
					if(direction == rightHard) {

					}
					direction = leftSoft;

				}
				if (rightColor > satThreshold && leftColor < satThreshold) {
					// turn right soft, right is black
					direction = rightSoft;

				}
			}
		}

	}
	releaseCPU();

}

task main()
{

	startTask(moveSense);
	while(true) {
		setMotorSync(LeftMotor, RightMotor, direction, 20);
		wait1Msec(10);		//Run for TENTH second

	}
	releaseCPU();


}
