#pragma config(Sensor, S1,     MoveForward,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          LeftMove,      tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          BeltControler, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Conveyor,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          RightMove,     tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	int integerrrr = getMotorEncoder(BeltControler);
	setMotorSpeed(BeltControler,0);
	setMotorSpeed(Conveyor,integerrrr);
	if(MoveForward) {
		setMotorSync(LeftMove, RightMove, 100, 1);
	} else {
		setMotorSync(LeftMove, RightMove,  0, 1);
	}
}
}
