#pragma config(Sensor, S1,     WallSensor,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ColorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     BallSensor,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorB,          ClawMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          ConveyMotor,   tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorNXT, openLoop, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This file locates a ball

// Including the ball file
//#include "FinallyHelpUs2v1.c"

// Including the going back home file
//#include "FinallyHelpUs3v1.c"



//This is the set threshold I think we got somewhere from 40 to 50 will work

int minDist = 5;
int maxDist = 15;
int speedMotor = 85;
int speedDown = 25;
int speedClaw = 75;
int speedHold = 5;
int direction = 1;

enum Directions
{
	forwardDir = 0,
	leftSoft = 25,
	rightSoft = -25,
	leftHard = 75,
	rightHard = -75
};

enum Colors
{
	yellow = 0,
	red = 1
};

enum Speed
{
	normal = -40,
	softTurn = -30,
	hardTurn = -20,
	reverseNormal = 40,
	stopMovement = 0
};

// Top distance sensor
bool enableDistSensor = false;
int stateDistSensor = 0;

// Bottom distance sensor
bool enableDistSensor2 = false;
int stateDistSensor2 = 0;

// Color sensor to detect ball color
bool enableColorSensor = false;
bool stateColorSensor = false;

enum SensorValues
{
	good,
	tooClose
};

int test;
int timer;
int timerClaw;
int temp = 0;

task main()
{

	test = 2;

	direction = 0;

	enableDistSensor = true;
	enableDistSensor2 = true;
	enableColorSensor = true;
	timer = 0;
	timerClaw = 0;

	while(true) {
		if (test == 1) {
				setMotorSync(LeftMotor, RightMotor, direction, speedMotor);
	  }
	  if (test == 2) {
	  	/*if (timer < 100) {
				setMotor(ConveyMotor, speedMotor);
				timer = timer + 1;
				}
				if ((timer < 400) && (timer >= 100)) {
					setMotor(ConveyMotor, -1*speedDown);
					timer = timer + 1;
				}
				if (timer >= 400){
					timer = 0;
				}*/



				temp = getMotorEncoder(ConveyMotor);
				if (temp < 75) {
				setMotor(ConveyMotor, speedMotor);
				timer = timer + 1;

				}
				else {
				setMotor(ConveyMotor, speedHold);

				}



	  	/*if (timerClaw < 100) {
	  		setMotor(ClawMotor, speedClaw);
				timerClaw = timerClaw + 1;
				}
				if ((timerClaw < 400) && (timerClaw >= 100)) {
					setMotor(ClawMotor, -1*speedClaw);
					timerClaw = timerClaw + 1;
				}
				if (timerClaw >= 400){
					timerClaw = 0;
				}*/
			}
	  if (test == 3) {
				setMotor(ClawMotor, speedMotor);
	  }
		wait1Msec(5);
	}
	releaseCPU();


}
